project:
  type: website

execute: 
  freeze: auto

website:
  site-url: https://econmaett.github.io/
  announcement: 
    icon: info-cirle
    dismissable: true
    content: "**Alert** - this site is currently under construction"
    type: info
    position: below-navbar
  title: "Home"
  description: "econmaett blog"
  twitter-card: true
  open-graph: true
  navbar:
    title: "EconMaett"
    background: light
    border: false
    style: "docked"
    search: false
    left: 
      - text: "Blog"
        icon: feather
        href: blog/index.qmd
      - text: "Projects"
        icon: gear
        href: projects/index.qmd
      - text: "Uses"
        icon: tools
        href: uses/index.qmd
    right:
      - text: "RSS"
        icon: rss
        href: blog/index.xml
      - text: "Talks"
        icon: megaphone
        href: talks/index.qmd
    tools:
      - icon: github
        href: https://github.com/EconMaett/econmaett.github.io

format:
  html:
    theme: [cosmo, styles.scss]
